# Generated by Django 5.2.13 on 2026-06-22 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_ranking_leaderboard_and_testresult_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='users.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Administrador'), ('ADMIN', 'Admin'), ('APRENDIZ', 'Aprendiz'), ('MONITOR', 'Monitor'), ('INSTRUCTOR', 'Instructor')], max_length=50),
        ),
    ]
